---
bibliography: references.bib
# suppress-bibliography: true
---


## The Challenge of Fish Nomenclature Conflicts

Several scientific investigations rely on accurate species identification and distribution data to draw conclusions across a wide range of research topics. This includes descriptive taxonomic and/or molecular identification studies as well as more complex modeling of species distribution over time to formulate assumptions. In any case, both approaches require robust and accurate species identification as a prerequisite. However, to ensure the reliability of species databases, innovative tools capable of addressing these challenges are needed. From a taxonomic perspective, challenges also persist regarding the incorporation of newly discovered taxa into these databases, alongside concerns about the reliability of the information contained therein, particularly considering that **these resources are mainly accessed by non-taxonomist end-users** [@ebach_impediments_2011]. This is an important aspect since several commonly used databases are not synchronous regarding species status updates.

The primary route for accessing taxonomic information relies on public databases, accessible to both taxonomists and non-taxonomists. These databases are hosted on web platforms like FishBase and Eschmeyer's Catalog of Fishes. Additionally, there are specific packages designed to curate and construct local species databases. However, **a challenge arises in validating species nomenclature from databases that do not synchronously update with species status changes**, especially for occurrence entries made by non-taxonomist users without cross-verification. To mitigate errors in data entry into these databases, several potential solutions have emerged. These solutions include the adoption of molecular identification techniques such as DNA barcoding, which facilitates species identification [@desalle_review_2019], and the expansion of taxonomic expertise through the training of more taxonomists. *Taxonomists play a crucial role in reviewing and validating species identification and nomenclature before new data are added to these databases* [@ebach_impediments_2011].

The correct identification and classification of organisms present multiple challenges, and their impact varies depending on the scientific, social, and political context. Poor taxonomic hypotheses, for instance, can result in misguided conservation priorities. The differentiation and discovery of species, while distinct terms, rely heavily on the foundation of trustworthy pre-existing information, which is predominantly accessed through these databases. Despite the partial automation of certain processes, taxonomic scrutiny remains important, particularly for taxonomic groups that remain incompletely understood. Consequently, the development of tools aimed at rectifying and validating data within cyber-infrastructures used for disseminating taxonomic information to end-users is important [@de_carvalho_revisiting_2005; @de_carvalho_taxonomic_2007]. This is especially true given that the majority of end-users lack taxonomic expertise and often need to integrate data from various databases into a unique dataset for posterior analysis.

In light of this, the demand for automation is increasing in the era of big data. Processing such data needs highly specialized tools that can be customized by end-users to align with their requirements. These tools have the potential to not only flag incorrect species status but also propose possible corrections, thereby contributing to the generation of more reliable data. The main challenge is taxonomic harmonization, the process of matching species names with those from a reference database, if not the main one, and checking their status. To avoid reinventing the wheel, the primary step is combining existing tools into **a unified solution that facilitates a “clean” and streamlined workflow for harmonizing taxonomic information**, making it accessible for different types of research. This necessitates the fusion of web knowledge, biological background, and programming development skills, enabling the processing and organization of online data to create an accessible resource [@grenie_harmonizing_2023].

Here, we introduce an R package designed for managing fish nomenclature data. Our goal was to process the data to generate a species list as curated and updated as possible. Additionally, we provide functions to update the status and nomenclature of species in occurrence datasets from the Global Biodiversity Information Facility (GBIF), and to interpret and compare species input data. To test `rFishStatus`, we used the Design Science Research Methodology (DSRM), following specific guidelines [@lacerda_design_2013; @hevner_design_2010; @peffers_design_2007]. The primary objective was to address the challenges associated with curating input lists of fish species, either sourced from users or occurrence datasets. The usage of the package is demonstrated across various scenarios.
